openapi: 3.1.0
info:
  version: 1.0.0
  title: Leleka App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Leleka App

tags:
  - name: Auth
    description: Auth operations
  - name: Diaries
    description: Diary operations.
  - name: Users
    description: Users operations

servers:
  - url: https://gitpub-backend-qq3d.onrender.com
    description: Production server
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /api/auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /api/auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  /api/diaries:
    get:
      $ref: ../swagger/paths/diary/get.yaml
    post:
      $ref: ../swagger/paths/diary/post.yaml

  /api/diaries/{diaryId}:
    patch:
      $ref: ../swagger/paths/diary/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/diary/{id}/delete.yaml


  /api/users:
    patch:
      $ref: ../swagger/paths/user/patchUser.yaml
  /api/users/me:
    get:
      $ref: ../swagger/paths/user/getUser.yaml
  /api/users/avatar:
    post:
      $ref: ../swagger/paths/user/patchAvatar.yaml

      # ======================== WEEKS ========================

  /api/weeks/current:
    get:
      $ref: ../swagger/paths/weeks/current.yaml

  /api/weeks/current/public:
    get:
      $ref: ../swagger/paths/weeks/currentPublic.yaml

  /api/weeks/{weekNumber}:
    get:
      $ref: ../swagger/paths/weeks/week.yaml

  /api/weeks/{weekNumber}/mom:
    get:
      $ref: ../swagger/paths/weeks/{weekNumber}/mom.yaml

  /api/weeks/{weekNumber}/baby:
    get:
      $ref: ../swagger/paths/weeks/{weekNumber}/baby.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      $ref: ../swagger/components/schemas/user.yaml
    Diary:
      $ref: ../swagger/components/schemas/diary.yaml
    DiaryUpdate:
      $ref: ../swagger/components/schemas/diaryUpdate.yaml
