openapi: 3.0.0
info:
  title: Gitpub Users API
  version: 1.0.0
  description: >
    Users API для отримання та оновлення інформації про користувача.
    Всі роутери приватні — потрібен accessToken.

servers:
  - url: http://localhost:3000

tags:
  - name: Users
    description: Операції з профілем користувача

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Unauthorized:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
              message:
                type: string
              data:
                type: string
                nullable: true
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
        avatar:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    UpdateUserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        accessToken:
          type: string

security:
  - bearerAuth: []

paths:
  /api/users/me:
    get:
      tags:
        - Users
      summary: Get current user info
      description: Отримати інформацію про поточного користувача
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Дані юзера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/users:
    patch:
      tags:
        - Users
      summary: Update current user's data
      description: Оновити імʼя чи email користувача. Повертає новий accessToken.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Оновлені дані юзера та новий токен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/users/avatar:
    post:
      tags:
        - Users
      summary: Update avatar
      description: Оновити аватар користувача (файл jpeg/png). Повертає шлях до аватару.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        '200':
          description: Шлях до аватару
          content:
            application/json:
              schema:
                type: object
                properties:
                  avatar:
                    type: string
        '401':
          $ref: '#/components/responses/Unauthorized'
