openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of App
tags:
  - name: Contacts
    description:
  - name: Auth
    description: Auth operations.
servers:
  - url:
    description: Production server
  - url: http://localhost:3000
    description: Local development server
paths:


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
